tool/markdown2ctags/markdown2ctags.py

This fixes an issue where comments inside GitHub Flavored Markdown code
blocks would be seen as section headers.

Update to v0.1.2 of markdown2ctags.

---

doc/notes.txt
tool/rst2ctags/rst2ctags.py

rst2ctags now works with headings that contain UTF-8 characters.

Update rst2ctags to v0.1.4.

---

vimrc

I haven't tried detecting whether we are in VirtualBox--I simply don't use it much.  But I'll keep it in mind if I happen to be messing with things at work and find myself using it.

Provide better default font sizes based on platform.

---

filetype.vim

I use coverage a fair amount in Python projects, and this is nice to have.  I've had it for quite some time locally, but figured it was good to share. :-)

Set the filetype .coveragerc to cfg.

---

ftplugin/ocaml_enhcomm.vim
ftplugin/php_enhcomm.vim

Randomly started editing php files and was getting an error in ftplugin/php_enhcomm.vim.  A little digging showed that ftplugin/php_enhcomm.vim (actually the remaining files in ftplugin) were from the Enhanced Commentify plugin which is not included in vimfiles.
I confirmed removing these files addresses the php file error on startup.  I believe it is safe to delete the other file as well as I see ocaml mentioned in tcomment.

Removed "leftover" Enhanced Commentify files.

---

bundle/togglecursor/doc/tags
bundle/togglecursor/doc/togglecursor.txt
bundle/togglecursor/plugin/togglecursor.vim
doc/notes.txt

This adds support for enabling cursor changing under Neovim, VTE3 support, along with better XTerm support.  It also allows you to force the particular kind of escape sequence used, if your terminal is not automatically detected.
Note: the new versios does change the default cursors to be blinking to better match gvim's behavior.

Update to v0.5.0 of vim-togglecursor.

---

bundle/session/INSTALL.md
bundle/session/README.md
bundle/session/autoload/xolox/session.vim
bundle/session/doc/session.txt
bundle/session/doc/tags
doc/notes.txt
vimrc

Prior to this version, vim-session would unconditionally save and restore the guifont.  Peter added a feature for me so that we could disable saving the guifont in the session file (`g:session_persist_font`).  This means that current sessions will either need to remove the line, or re-save the session, but this option will keep it out of future session files.  I think this is better behavior overall, since I'd like a change to my default font to be reflected everywhere.

Update vim-session to 2.13.

---

bundle/powerline/autoload/Pl/Parser.vim
doc/notes.txt
vimrc

While trying to work on a replacement fileinfo segment that does not use
a bolded LN symbol (to make it work better with the Hack typeface), I
noticed that the BRANCH and LINE symbols would eventually become [''].
It's still not entirely clear why this is happening, but it smells like
something is mutating a reference.  As a result, let's create a copy of
the arg in Pl#Parser#ParseChars() and return that instead.  This fix
allows everything to work correctly again.

Fix a powerline bug where symbols would disappear from the dictionary.

---

vimrc

In the logic to disable airline, `g:Airline_loaded` is set in an
attempt to prevent the plugin from loading which was not working as
expected.  Looking through the plugin, loading is controlled via
`g:loaded_airline`.  This request updates the logic to set the
appropriate variable to prevent airline from loading.

Set `loaded_airline` to disable airline

---

doc/notes.txt
vimrc

I refactored the detection of whether a font supports Powerline symbols
because the Hack font has them built-in and doesn't have Powerline in
the name.
This also adds an AirlineCustomizeSymbols command so that users can
override and customize the symbols.

Add support for knowing when to use powerline symbols with airline.

---

tool/rst2ctags/rst2ctags.py

This version changes the shebang line to use python2, and ensures the
heading characters are homogeneous.

Update rst2ctags to v0.1.5.

---

tool/markdown2ctags/markdown2ctags.py

This fixes a bug when nesting sections that were more than one-level
apart from the current section (putting h4's in h2's).

Update markdown2ctags to 0.1.3.

---

vimrc

At some point in Vim 8.0 they stopped allowing the :lopen command from
being called inside an autocmd.  Unfortunately, this causes an error
trace and it doesn't fail in a way that allows us to distinguish the
type of window it is either.  However, a new built-in was added to allow
us to get the window id and look up whether it's a quickfix or loclist.
So we'll prefer that technique when available, and when it isn't we fall
back to the old technique.  win_getid() first appeared in 7.4.2063, so
there should not be any gaps where both techniques may fail.

Make IsQuickFixWin() work correctly in newer versions of Vim.

---

bundle/togglecursor/plugin/togglecursor.vim
doc/notes.txt

It now avoids some extra work when Vim supports the t_SR option.

Upgrade vim-togglecursor to 0.5.2.

---

vimrc

If you don't have ale enabled, then you end up with an ugly error
message:
Error detected while processing /Users/jszakmeister/.vim/vimrc:
line 3348:
E117: Unknown function: ale#Escape
E15: Invalid expression: '--ignore-messages ' . ale#Escape( 'Duplicate implicit target name:')
This happens because ale is not loaded by default (since we're
experimenting with it) and `ale#Escape` is not defined.

Guard the ale settings since we make use of some ale functions.

---

vimrc

We base our Markdown embedded languages on the reStructuredText ones by
default, so we need to same ini mapping done in reStructuedText when
setting up ini syntax support in Markdown.

Support .ini syntax in Markdown files.

---

vimrc

These options became available in 7.4.775.  Check the version and ensure
vim supports the options before adding them to `completeopt`.

Only add noselect and noinsert to completeopt when vim supports it.

---

vimrc

Ran into this issue on a VM with an old version of Vim. :-)

Only set termguicolors if Vim supports the feature.

---

doc/notes.txt
tool/markdown2ctags/markdown2ctags.py
tool/rst2ctags/rst2ctags.py

This version doesn't use pkg_resources anymore, saving us on start up
time.

Upgrade rst2ctags and markdown2ctags.

---

CHANGES.txt
vimrc

Tested on MacOS BigSur and Catalina.  Also, tested on Ubuntu 20.04 with custom built (`buildtool`) vim:
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  5 2021 16:21:06)
Included patches: 1-2467
Compiled by vim@drmikehenry.com
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse …
```

Allow vimfiles to work with native macOS vim diffopt
